sudo: false
language: python
matrix:
  include:
    - os: linux
      python: 2.7
      env: TOX_ENV=py27
    - os: linux
      python: 3.4
      env: TOX_ENV=py34
    - os: linux
      python: 3.5
      env: TOX_ENV=py35
    - os: linux
      python: 3.6
      env: TOX_ENV=py36
    - os: linux
      python: pypy
      env: TOX_ENV=pypy
    - os: osx
      language: generic
      env: TOX_ENV=py27
      before_install:
        - brew update
        - brew upgrade python
        - python3 -m venv venv
        - source venv/bin/activate
    - os: linux
      python: 3.6
      env: TOX_ENV=with_optional
    - os: linux
      python: 2.7
      env: TOX_ENV=runner
    - os: linux
      python: 3.6
      env: TOX_ENV=lint
    - os: linux
      python: 2.7
      env: TOX_ENV=integration
    - os: linux
      python: 2.7
      env: TOX_ENV=coverage
install:
  - pip install Babel tox
script: tox -e $TOX_ENV
